### ISSUE TITLE
GrandOrgue - Export Issues

### ISSUE THREAD

**Issue by sound8** [davy7125/polyphone#173]
When you try to convert GrandOrgue instruments to Soundfonts some issues occur....

1.) The resulting exported Soundfont ends up with a lower attenuation (volume), quieter than the original GrandOrgue instruments volume.  Same thing that occurs with SFZ as mentioned here #147.

2.)  Also the notes shift an octave up or down (can't remember which)
So when you play the GrandOrgue instrument in Polyphone they are set at a specific octave, but the converted Soundfont when you play the same physical keyboard note is off by an octave up or down (again sorry can't remember which)

3.) Currently cannot use the Command Line Export option in Polyphone to convert GrandOrgue to either SFZ or Soundfont.
Would it be possible to add the ability to do this?

Thank You for all your help.

**Comment by davy7125** [comment]
Several subjects in this ticket (please open 1 ticket per subject).

1.1 Maybe GrandOrgue increases the volume and Polyphone doesn't get the configuration. But generally speaking, Polyphone doesn't have to be aware of such configuration, it is a tool for editing soundfonts, independently of other applications.
1.2 The sfz export should have been fixed with the recent changes in Polyphone (will be in the next version).
2 I would need an example for reproducing the bug
3 Fixed!
