### ISSUE TITLE
[BUG] Polyphone allows to modulate data increment

### ISSUE THREAD

**Issue by spessasus** [davy7125/polyphone#202]
While sfspec24.pdf page 40 doesn't mention data increment and decrement specifically, it says that data entry LSB and MSB cannot be modulated. Same with Registered parameters. 

It only makes sense to exclude data increment and decrement as well. (How would that even work?) But currently Polyphone allows us to modulate data increment and decrement, which can lead to unexpected behavior.

![image](https://github.com/user-attachments/assets/ec654c5c-d622-4977-9dd4-5a7494be5145)

Also thanks for fixing the bugs I've reported so far :-)

**Comment by davy7125** [comment]
Extract of the specifications:

_Note that in this case where C is set to 1, index values 0, 6, 32, 38, 98 through 101, and 120 through 127 are ILLEGAL due to their nature as a MIDI functions rather than true MIDI controllers. Also, index values 33 through 63 should be reserved for LSB contributions of controller indices 1 through 31. If these index values are encountered, the entire modulator structure should be ignored._

So I remove all of them, including data increment / decrement.

You are welcome, any help is appreciated
