### ISSUE TITLE
[BUG] Random crash when copying instrument to other file

### ISSUE THREAD

**Issue by LoveBodhi** [davy7125/polyphone#231]

**Comment by davy7125** [comment]
I cannot reproduce the bug. Could you please add these details:
- Which version of Polyphone are you using? (this is likely the latest according to your other bug report but just to be sure)
- Is the bug appearing only when existing samples and / or instruments are replaced? Or it doesn't matter? I'm trying to find out if the bug is in the replacement of a sample, the replacement of an instrument, or something more general.
- Which OS are you using?

**Comment by davy7125** [comment]
Also: is it implying the copy of stereo samples? Do the two channels right / left of these samples have the same length?
