### ISSUE TITLE
Allow multiple modulators as sources of another modulator

### ISSUE THREAD

**Issue by davy7125** [davy7125/polyphone#49]

**Comment by jjceresa** [comment]
Assuming two linked modulators `m1` and `m2` with m1 been destination of m2  `(m2->m1)`
1)Actual behaviour:
- m1 `source listbox conrtol` shows `modulateurs: # 2`. This is inappropriate because any number of modulators can have m1 as destination (according to SF specifications).
2.1)Correct behaviour
- m1 `source listbox conrtol` should shows `link` or `lié` (in french) that means that any numbers of modulators have m1 as destination.
- Polyphone should not allow the user to set a connection from a modulator source (i.e from m1 source) to another modulator (because this is a non sense).
- Polyphone should ONLY allow the user to set a connection from a modulator destination (i.e m2 destination). In this case,  m2 ` destination listbox conrtol` shows `modulateurs: # 1` (as it is the case in actual behaviour).
2.2) Correct behaviour
When two modulator are linked (ie as in the previous example `(m2->m1)`). 
- If the user wants to delete one modulator (i.e m1), the other modulator (i.e m2) should be keep in its state and Polyphone should not attempt to remove automatically m2. This gives the user the possibility to connect m2 destination to another modulator.
- Similarly , if the user delete m2, the other modulator (i.e m1) should be keep in its state even if the user doesn't intend to set  another modulator destination to m1.
In others words, it isn't important if a modulator is `without destination` or `without source` or connected in an `absurd circular manner`, because is up to the synthesizer to get rid of these invalids modulators at soundfont loading time (SF specifications). Consequently Polyphone should not attempt to assist the user because it is useless.

Consequently it seems easy (i hope) to fix this issue inside Polyphone. Here i have a synthesiser (fluidsynth) with full SF linked modulators capabilities. So i am ready to verify and test any fix.

**Comment by davy7125** [comment]
@jjceresa thanks a lot for the details. I fixed this issue and you will be able to test as soon as there is a beta (I don't know when yet).

**Comment by jjceresa** [comment]
>I fixed this issue and you will be able to test as soon as there is a beta (I don't know when yet).

Thanks you Davy. Here, I am running on Windows XP. Hope I could test this. I would be happy to give any feedback.

**Comment by jjceresa** [comment]
Windows installer version 2.1 or (beta 2.1) fails to install on Windows XP. Unfortunately, I couldn't test this new future.

**Comment by jjceresa** [comment]
Windows installer version 2.1 or (beta 2.1) fails to install on Windows XP. Unfortunately, I couldn't test this new feature.
