### ISSUE TITLE
Current GUI Difficulties

### ISSUE THREAD

**Issue by PZBH6408** [davy7125/polyphone#58]
Polyphone 2.0
New GUI for Polyphone is difficult to use and confusing. Elements break when it is inside a small window. Public Repository screen wastes network data.
Polyphone 1.9
GUI was professional. This version can no longer be built because of librtmidi3 -> librtmidi4.

**Comment by davy7125** [comment]
Could you please be more specific regarding the elements that break? (screen resolution and how to reproduce it).

You can set the flag USE_LOCAL_RTMIDI so that no rtmidi dependency is necessary. However this should work with version 4 (I updated the files and it still compiles).

Downloading the soundfont list uses 104kB... and will not stop Polyphone if the network is not available.
https://www.polyphone-soundfonts.com/en/api/soundfonts/list

**Comment by PZBH6408** [comment]
Element Break:
![image](https://user-images.githubusercontent.com/51990547/60070808-64c59800-975b-11e9-962d-5e61c6bbe1c7.png)
The virtual keyboard settings, the online repository menu and the create an account button have text outside of the box.

Element Break 2:
![image](https://user-images.githubusercontent.com/51990547/60070898-b110d800-975b-11e9-855c-7fa4a9be8ab2.png)
The menu to the left - instruments and the text to the right - editing software have text clipping.

RTMIDI:
![image](https://user-images.githubusercontent.com/51990547/60070669-ce917200-975a-11e9-90aa-784261d6b13b.png)

**Comment by davy7125** [comment]
Thank you for the details. From what I see, Polyphone cannot be installed (not built) because of a missing dependency. For this you could either try to force the install of librtmidi3 in your distribution, or build Polyphone for your system with Qt Creator, or try to find a package (or a maintainer for the package) corresponding to your distribution.

I will fix the GUI issues.

**Comment by PZBH6408** [comment]
Thank you.

**Comment by davy7125** [comment]
@PZBH6408 
I have other questions:
- what is the resolution of your screen?
- what is your distribution?
- have you configured your system to increase the font size?

**Comment by PZBH6408** [comment]
> @PZBH6408
> I have other questions:
> 
>     * what is the resolution of your screen?
> 
>     * what is your distribution?
> 
>     * have you configured your system to increase the font size?

What is the resolution of my screen?
I have 2 4k-monitors. However, I like to run applications in the smallest window possible so I can have many windows on screen at once.

What is my distribution?
Linux Mint 19.1 xfce

Have I configured my system to increase the font size?
No. It is a default install of the distribution.

**Comment by davy7125** [comment]
Thanks!
