### ISSUE TITLE
This repository is mis-labeled: 'git describe --tags' doesn't return a tag for the last revision

### ISSUE THREAD

**Issue by yurivict** [davy7125/polyphone#60]
```
Cloning into 'polyphone'...
remote: Enumerating objects: 87, done.
remote: Counting objects: 100% (87/87), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 15404 (delta 46), reused 42 (delta 27), pack-reused 15317
Receiving objects: 100% (15404/15404), 20.99 MiB | 7.94 MiB/s, done.
Resolving deltas: 100% (11163/11163), done.
fatal: No tags can describe 'd7459fa04ae4fc47335e4809547999338090fd7e'.
Try --always, or create some tags.
```

Usually, it returns something like this ```2.0.1-{N}-g{hash}```.

**Comment by davy7125** [comment]
I cleaned the repository because of #55 and I probably lost a continuity with previous commits. Maybe this will be fixed automatically when I'll create the next tag 2.1?
The next version 2.1 is still in development, I plan to release it around September. It is ok to wait? I prefer not creating a premature tag before the real version.

**Comment by davy7125** [comment]
Probably fixed with the new version
