### ISSUE TITLE
Loop scan

### ISSUE THREAD

**Issue by davy7125** [davy7125/polyphone#68]
Add a function that scans for loop, that could find a good loop before we need the use of a cross-fade.
https://www.polyphone-soundfonts.com/en/forum/feature-requests/340-manual-crossfade

**Comment by davy7125** [comment]
Source from LoopAuditioneer might help:
https://sourceforge.net/p/loopauditioneer/code/HEAD/tree/trunk/src/

**Comment by mmontag** [comment]
+1, improved loop editing would be really helpful.

Some ideas (sorry if Polyphone already has these):
- Optimize waveform rendering.
- Make interaction with loop points easier. The UI feels clunky; the entire loop region should be draggable in addition to draggable start and end handles.
- Detect fundamental frequency of the sample and make a checkbox to ensure the loop length is a multiple of the fundamental period (so that loops don't go out of tune). The loop endpoints should still be draggable, but snap to this multiple.
- Automatic loop finder button: automatically detect loops according to some objective function, or at least make a few guesses and suggest them for the user.

**Comment by davy7125** [comment]
The goal in Polyphone is to find a loop with a simple tool. The algorithm is now improved and find the best correlations between points that are not close to each other.

Regarding the draggable bar... I find faster a simple click to move the bar.
And I find it better also to let the user move freely the bar. Sometimes the sound is better with +1 or -1 (for high pitches)
